import type { ReactNode } from 'react';
import type { ConsoleSettings } from '../../src/console/settings.ts';
import { SettingsEditor } from './settings-editor.tsx';
import { RoleAssignments } from './role-assignments.tsx';
import { settingLabels } from './settings-controls.tsx';

const providerNames = { codex: 'Codex', claude: 'Claude Code', cursor: 'Cursor' };


function Fields({ values }: { values: object }) {
  return <dl className="settings-fields">{Object.entries(values).filter(([key]) => key in settingLabels).map(([key, value]) => <div key={key}><dt>{settingLabels[key]}</dt><dd>{typeof value === 'boolean' ? (value ? 'Yes' : 'No') : typeof value === 'number' ? value.toLocaleString() : String(value)}</dd></div>)}</dl>;
}

export function Settings({ settings, connectionSettings, token = '', onSaved = () => {} }: { settings?: ConsoleSettings; connectionSettings?: ReactNode; token?: string; onSaved?: () => void }) {
  if (!settings) return <section className="workspace"><section className="panel"><h2>Settings unavailable</h2><p>This Console service has not published its configuration. Update and restart the local service to display provider and factory settings.</p>{connectionSettings}</section></section>;
  if (settings.factory.catalogConfigured === false) return <section className="workspace settings-page">
    <section className="panel settings-intro"><div><h2>Factory settings need a catalog</h2><p>This Console is running with its operational connection settings, but the factory catalog was not included. There are no factory defaults, providers, products, or pods available to edit.</p></div><span className="settings-badge">Editing unavailable</span></section>
    <section className="panel panel-support"><h2>Restore factory settings</h2><p>Stop the Console, add the approved factory configuration as <code>factoryConfiguration</code> in the same local Console JSON file, then restart the Console from that file.</p><details id="settings-configuration-help" open><summary>What the configuration must contain</summary><p>Use the existing approved factory catalog. Its <code>factory.id</code> must match this Console’s factory ID, and it must include the factory defaults, providers, environments, products, and pods. Do not enter provider credentials, tokens, or runtime routes here.</p><p>This Console cannot select a file or import a catalog from the browser. That keeps local paths and owner-controlled configuration out of the browser.</p></details></section>
    <section className="panel"><h2>Console connection</h2><p>Local command authorization for this browser session.</p>{connectionSettings}</section>
  </section>;
  return <section className="workspace settings-page">
    <section className="panel settings-intro"><div><h2>Your factory, configured</h2><p>{settings.factory.name} · Factory-wide settings, independent of the Work filters.</p></div><span className="settings-badge">Currently running</span></section>
    {settings.persistence?.restartRequired && <section className="panel settings-restart" role="status"><strong>Saved changes are waiting for restart</strong><p>The values below are still the loaded configuration. Reopen the editor to see saved changes.</p></section>}
    {settings.persistence?.editable ? <SettingsEditor settings={settings} token={token} onSaved={onSaved} /> : <section className="panel"><p>Editing is unavailable for this service. Start the Console from an owner-controlled configuration file to enable persistent settings.</p></section>}
    <section className="settings-providers" aria-label="Providers">{settings.providers.map((provider) => <article className="panel provider-card" key={provider.id}>
      <div className="panel-heading"><h2>{providerNames[provider.id]}</h2><span className={`settings-badge ${provider.enabled ? 'route-enabled' : ''}`}>{provider.enabled ? 'Execution configured' : provider.configured ? 'Catalog only' : 'Not configured'}</span></div>
      <dl className="settings-fields"><div><dt>Factory catalog</dt><dd>{provider.configured ? 'Included' : 'Not included'}</dd></div><div><dt>Login status</dt><dd>Unverified</dd></div><div><dt>Execution profile</dt><dd>{provider.routes.map((route) => route.profile).join(', ') || 'No runtime route'}</dd></div><div><dt>Compatible models</dt><dd>{provider.routes.flatMap((route) => route.compatibleModels ?? []).join(', ') || 'Not specified'}</dd></div></dl>
      <p className="settings-footnote">{provider.authentication.detail}</p>
      <details><summary>Declared capabilities</summary><p>{provider.capabilities.join(', ') || 'No capabilities declared.'}</p></details>
    </article>)}</section>
    {settings.factory.defaults && <section className="panel panel-support"><h2>Factory defaults</h2><RoleAssignments assignments={settings.factory.defaults.roleAssignments} settings={settings} /><div className="settings-assignment"><span>Provider <strong>{settings.factory.defaults.providerId || 'Not assigned'}</strong></span><span>Environment <strong>{settings.factory.defaults.environmentId || 'Not assigned'}</strong></span><span>Profile <strong>{settings.factory.defaults.executionProfile}</strong></span></div><details><summary>Default limits & approval policy</summary><div className="settings-grid"><Fields values={settings.factory.defaults.budget} /><Fields values={settings.factory.defaults.authority} /></div></details></section>}
    <div className="settings-grid">
      <section className="panel panel-support"><h2>Resources & limits</h2><p>Coordinator limits currently loaded by this service.</p><Fields values={settings.resourceLimits} /><p className="settings-footnote">Configuration limits are not usage measurements or subscription balances.</p></section>
      <section className="panel"><h2>Environments & maintenance</h2><dl className="settings-fields">{settings.environments.map((environment) => <div key={environment.id}><dt>{environment.id}</dt><dd>{environment.kind}</dd></div>)}<div><dt>Routine maintenance</dt><dd>{settings.recovery.configured ? 'Configured' : 'Not configured'}</dd></div><div><dt>GM mode</dt><dd>{(settings.generalManager?.mode ?? 'not_configured').replaceAll('_', ' ')}</dd></div><div><dt>GM review routes</dt><dd>{settings.generalManager?.reviewRouteCount ?? 0}</dd></div><div><dt>GM schedule</dt><dd>{settings.generalManager?.schedule?.enabled ? `${settings.generalManager.schedule.localTime} ${settings.generalManager.schedule.timezone}` : 'Not configured'}</dd></div></dl><p className="settings-footnote">{settings.recovery.routineActions.join(', ').replaceAll('_', ' ') || 'No routine maintenance actions are configured.'} This does not imply rollback is enabled. Scheduler installation and health are observed separately from configuration.</p></section>
    </div>
    <section className="panel"><h2>Products & pod configuration</h2><p>Resolved assignments and policies, including inherited values.</p>{settings.products.length === 0 ? <p>No product configuration was supplied.</p> : settings.products.map((product) => <details className="settings-product" key={product.id} open><summary>{product.name}<span>{product.pods.length} pod{product.pods.length === 1 ? '' : 's'}</span></summary><div className="settings-assignment"><span>Provider <strong>{product.providerId || 'Not assigned'}</strong></span><span>Environment <strong>{product.environmentId || 'Not assigned'}</strong></span><span>Profile <strong>{product.executionProfile}</strong></span></div><RoleAssignments assignments={product.roleAssignments} settings={settings} /><details><summary>Product limits & approval policy</summary><div className="settings-grid"><Fields values={product.budget} /><Fields values={product.authority} /></div></details>{product.pods.map((pod) => <details className="settings-pod" key={pod.id}><summary>{pod.id}</summary><RoleAssignments assignments={pod.roleAssignments} settings={settings} /><p>Provider: {pod.providerId || 'Not assigned'} · Environment: {pod.environmentId || 'Not assigned'} · Profile: {pod.executionProfile}</p><div className="settings-grid"><Fields values={pod.budget} /><Fields values={pod.authority} /></div></details>)}</details>)}</section>
    <div className="settings-grid"><section className="panel panel-support"><h2>Apply saved changes</h2><p>After saving, stop and restart the Console using the same configuration file. Existing workers are not reconfigured by a save. Runtime routes, credential profiles, and new environments still require setup through your agent.</p><p>Provider login stays in each provider’s own CLI. Faktori never asks for subscription credentials here.</p></section><section className="panel"><h2>Console connection</h2><p>Local command authorization for this browser session.</p>{connectionSettings}</section></div>
  </section>;
}
